# Generated by Django 5.0.6 on 2024-08-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('probabilidade', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('classificacao', models.CharField(max_length=255)),
                ('projeto', models.CharField(max_length=255)),
                ('data_entrada', models.DateField()),
                ('impacto', models.CharField(max_length=255)),
                ('consequencia', models.CharField(max_length=255)),
                ('jalon_afetado', models.CharField(max_length=255)),
                ('metier', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Solucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(max_length=255)),
                ('probabilidade_residual', models.FloatField()),
                ('impacto_residual', models.CharField(max_length=255)),
                ('validacao_acao', models.CharField(max_length=255)),
                ('data_alerta', models.DateField()),
                ('nome_piloto', models.CharField(max_length=255)),
                ('captalizacao', models.BooleanField()),
                ('inicio_plano_acao', models.DateField()),
                ('acao', models.CharField(max_length=255)),
                ('comentario', models.CharField(max_length=255)),
                ('data_resolucao', models.DateField()),
                ('id_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.piloto')),
                ('id_risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.risco')),
            ],
        ),
        migrations.AddField(
            model_name='risco',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_backend.usuario', verbose_name='Usuário'),
        ),
    ]
